apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubenanny
  namespace: kubenanny-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubenanny
rules:
  - apiGroups: ["policy.kubenanny.io"]
    resources: ["egresspolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy.kubenanny.io"]
    resources: ["egresspolicies/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubenanny
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubenanny
subjects:
  - kind: ServiceAccount
    name: kubenanny
    namespace: kubenanny-system
